"""add_sandbox_tables

Revision ID: f79f4b742aba
Revises: 013
Create Date: 2026-03-24 22:40:44.792035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79f4b742aba'
down_revision: Union[str, None] = '013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cadence_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'APPROVED', 'REJECTED', name='sandbox_run_status'), nullable=False),
    sa.Column('lead_source', sa.Enum('REAL', 'SAMPLE', 'FICTITIOUS', name='sandbox_lead_source'), nullable=False),
    sa.Column('pipedrive_dry_run', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cadence_id'], ['cadences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_runs_cadence_id'), 'sandbox_runs', ['cadence_id'], unique=False)
    op.create_index(op.f('ix_sandbox_runs_tenant_id'), 'sandbox_runs', ['tenant_id'], unique=False)
    op.create_table('sandbox_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sandbox_run_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('fictitious_lead_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.Enum('LINKEDIN_CONNECT', 'LINKEDIN_DM', 'EMAIL', 'MANUAL_TASK', name='cadence_step_channel'), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('use_voice', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at_preview', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('audio_preview_url', sa.String(length=500), nullable=True),
    sa.Column('email_subject', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'GENERATED', 'APPROVED', 'REJECTED', name='sandbox_step_status'), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('simulated_reply', sa.Text(), nullable=True),
    sa.Column('simulated_intent', sa.Enum('INTEREST', 'OBJECTION', 'NOT_INTERESTED', 'NEUTRAL', 'OUT_OF_OFFICE', name='interaction_intent'), nullable=True),
    sa.Column('simulated_confidence', sa.Float(), nullable=True),
    sa.Column('simulated_reply_summary', sa.String(length=500), nullable=True),
    sa.Column('is_rate_limited', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_reason', sa.String(length=300), nullable=True),
    sa.Column('adjusted_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sandbox_run_id'], ['sandbox_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_steps_lead_id'), 'sandbox_steps', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sandbox_steps_sandbox_run_id'), 'sandbox_steps', ['sandbox_run_id'], unique=False)
    op.create_index(op.f('ix_sandbox_steps_tenant_id'), 'sandbox_steps', ['tenant_id'], unique=False)
    op.alter_column('audio_files', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="Nome amigável (ex: 'Abertura padrão')",
               existing_nullable=False)
    op.alter_column('audio_files', 's3_key',
               existing_type=sa.VARCHAR(length=500),
               comment='Chave do objeto no bucket S3',
               existing_nullable=False)
    op.alter_column('audio_files', 'url',
               existing_type=sa.VARCHAR(length=1000),
               comment='URL pública do arquivo',
               existing_nullable=False)
    op.alter_column('audio_files', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               comment='MIME type (ex: audio/mpeg, audio/wav)',
               existing_nullable=False)
    op.alter_column('audio_files', 'size_bytes',
               existing_type=sa.BIGINT(),
               comment='Tamanho do arquivo em bytes',
               existing_nullable=False)
    op.alter_column('audio_files', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Duração do áudio em segundos (preenchido se disponível)',
               existing_nullable=True)
    op.alter_column('audio_files', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='Idioma do áudio',
               existing_nullable=False)
    op.alter_column('audio_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audio_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cadence_steps', 'audio_file_id',
               existing_type=sa.UUID(),
               comment='Se preenchido, usa áudio pré-gravado ao invés de TTS',
               existing_nullable=True)
    op.drop_index('ix_cadence_steps_audio_file_id', table_name='cadence_steps')
    op.alter_column('cadences', 'lead_list_id',
               existing_type=sa.UUID(),
               comment='Lista de leads vinculada. NULL = sem lista.',
               existing_nullable=True)
    op.drop_index('ix_cadences_lead_list_id', table_name='cadences')
    op.alter_column('lead_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lead_lists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_lists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('lead_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index('ix_cadences_lead_list_id', 'cadences', ['lead_list_id'], unique=False)
    op.alter_column('cadences', 'lead_list_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Lista de leads vinculada. NULL = sem lista.',
               existing_nullable=True)
    op.create_index('ix_cadence_steps_audio_file_id', 'cadence_steps', ['audio_file_id'], unique=False)
    op.alter_column('cadence_steps', 'audio_file_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Se preenchido, usa áudio pré-gravado ao invés de TTS',
               existing_nullable=True)
    op.alter_column('audio_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audio_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audio_files', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'pt-BR'::character varying"),
               comment=None,
               existing_comment='Idioma do áudio',
               existing_nullable=False)
    op.alter_column('audio_files', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Duração do áudio em segundos (preenchido se disponível)',
               existing_nullable=True)
    op.alter_column('audio_files', 'size_bytes',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Tamanho do arquivo em bytes',
               existing_nullable=False)
    op.alter_column('audio_files', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'audio/mpeg'::character varying"),
               comment=None,
               existing_comment='MIME type (ex: audio/mpeg, audio/wav)',
               existing_nullable=False)
    op.alter_column('audio_files', 'url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='URL pública do arquivo',
               existing_nullable=False)
    op.alter_column('audio_files', 's3_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Chave do objeto no bucket S3',
               existing_nullable=False)
    op.alter_column('audio_files', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Nome amigável (ex: 'Abertura padrão')",
               existing_nullable=False)
    op.drop_index(op.f('ix_sandbox_steps_tenant_id'), table_name='sandbox_steps')
    op.drop_index(op.f('ix_sandbox_steps_sandbox_run_id'), table_name='sandbox_steps')
    op.drop_index(op.f('ix_sandbox_steps_lead_id'), table_name='sandbox_steps')
    op.drop_table('sandbox_steps')
    op.drop_index(op.f('ix_sandbox_runs_tenant_id'), table_name='sandbox_runs')
    op.drop_index(op.f('ix_sandbox_runs_cadence_id'), table_name='sandbox_runs')
    op.drop_table('sandbox_runs')
    # ### end Alembic commands ###
