"""add_saves_to_content_posts

Revision ID: 029fbde58dfb
Revises: 035
Create Date: 2026-04-05 15:40:15.804083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '029fbde58dfb'
down_revision: Union[str, None] = '035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_linkedin_accounts', 'li_at_cookie',
               existing_type=sa.VARCHAR(length=2000),
               comment='Cookie li_at criptografado com Fernet — usado para buscar métricas via Voyager API',
               existing_comment='Cookie li_at criptografado com Fernet para Voyager API (analytics pessoal)',
               existing_nullable=True)
    op.alter_column('content_linkedin_accounts', 'last_voyager_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp da última sincronização de métricas via Voyager API',
               existing_comment='Última sincronização de métricas via Voyager API',
               existing_nullable=True)
    op.add_column('content_posts', sa.Column('saves', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('sandbox_steps', 'composition_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Metadados de observabilidade usados na composição do step',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sandbox_steps', 'composition_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Metadados de observabilidade usados na composição do step',
               existing_nullable=True)
    op.drop_column('content_posts', 'saves')
    op.alter_column('content_linkedin_accounts', 'last_voyager_sync_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Última sincronização de métricas via Voyager API',
               existing_comment='Timestamp da última sincronização de métricas via Voyager API',
               existing_nullable=True)
    op.alter_column('content_linkedin_accounts', 'li_at_cookie',
               existing_type=sa.VARCHAR(length=2000),
               comment='Cookie li_at criptografado com Fernet para Voyager API (analytics pessoal)',
               existing_comment='Cookie li_at criptografado com Fernet — usado para buscar métricas via Voyager API',
               existing_nullable=True)
    # ### end Alembic commands ###
